### ISSUE TITLE
I don't have an assigned group.

### ISSUE THREAD

**Issue by duartegalvao** [KTH/devops-course#32]
I'm Duarte Galvão, at dadsg@kth.se, and I don't have an assigned group for any task.
Additionally, I wouldn't mind presenting next monday.

**Comment by gluckzhang** [comment]
Hi @duartegalvao , the pre-generated group sheets are the suggestion instead of the mandatory, you could directly organize groups by youself, [see the updated rules here](https://github.com/KTH/devops-course#group-rules).

If you would like to look for team members, you could create / search relevant issues :)
