### ISSUE TITLE
Feeling shared by many in the course about the onboarding 

### ISSUE THREAD

**Issue by Mema5** [KTH/devops-course#330]
Hello, 
I just wanted to share a feeling that seems to be shared among some students in the course.
This first lecture helped a lot to understand better the purpose, schedule and vision of this course. Thanks for the energy you put to answer our questions and try to clarify everything.
However I still feel a bit at a loss: we are supposed to already select a topic to work on without having even had the first lecture setting the boundaries of DevOps. It is maybe easy for some people that had a previous knowledge on the topic or knew what they were interested on before coming, but for others we just end out opening thousands of tabs, choosing and pairing up almost randomly.
It is too early for me to have any constructive suggestion on how to improve that, but I wanted to create a discussion and let you know that.

**Comment by gluckzhang** [comment]
Thanks @Mema5 for sharing this! We will discuss how to improve the onboarding experience.

Hi @monperrus @bbaudry , I would like to involve you into this topic. Maybe we could have a subset of topics which are recommended for the first task? Or we could suggest students to take a look at folder `contributions-2019` since we have already mentioned the goal in the README file (register one first task as a pull request on this repo).

**Comment by Mema5** [comment]
Thanks @gluckzhang  for your consideration!

- I was also thinking about showing in live a demo / presentation / tutorial and such during this first lecture. 
- A definition of DevOps and the different topics it touches could also be very helpful to help us grasping more the boundaries and opportunities.
- Other idea: sending an email beforehand to the people taking the course and ask them to have a look at some chosen resource in the repo. Personally I did not receive anything by email from you, but it is maybe because of late registration or something.

**Comment by gluckzhang** [comment]
Thanks @Mema5 for these suggestions!

> * I was also thinking about showing in live a demo / presentation / tutorial and such during this first lecture.

Agree, this helps a lot.

> * A definition of DevOps and the different topics it touches could also be very helpful to help us grasping more the boundaries and opportunities.

I think the second lecture will discuss more about the scrope of DevOps and related definitions. Probably we could provide a bit more introduction materials, just in order to help you choose the first task.

> * Other idea: sending an email beforehand to the people taking the course and ask them to have a look at some chosen resource in the repo. Personally I did not receive anything by email from you, but it is maybe because of late registration or something.

Good idea. I am not sure how early we could get registeration list (TAs don't have access to it). Will discuss this with Martin and Benoit later.

**Comment by EyuTes** [comment]
Do you need one more guy in your team?

**Comment by Mema5** [comment]
Have been discussed during the lecture in week2 (March 24th 2020). I close this issue.

**Comment by monperrus** [comment]
Perfect. We always keep time in the lecture to resolve and close pending issues. We wish you all a productive week!
