### ISSUE TITLE
Suitability of Topic: Chaos Engineering

### ISSUE THREAD

**Issue by nagavem** [KTH/devops-course#360]
Hej,

@gluckzhang 

My teammate and I have decided to take upon the topic of chaos engineering for the presentation. To be more specific namely : "Chaos Engineering Tools and Techniques". This topic is of particular interest to us and so far we have parsed through the following resources to get a rough idea of the same:-

- https://dius.com.au/resources/game-day/chaos-engineering-tools-techniques/
- https://www.gremlin.com/chaos-engineering/chaos-engineering-tools-comparison/
- https://techbeacon.com/app-dev-testing/chaos-engineering-testing-34-tools-tutorials

Is it fine to proceed with the above topic or should it be more specific in nature,please do let me know on the same.

**Comment by gluckzhang** [comment]
Hi @nagavem , thanks for creating such a discussion :)

I think that would be nice to go a bit deeper, after introducing the concepts and state of the art. Because if all the contents are general and high level, it may be difficult for you to fulfill some of the [grading criteria](https://github.com/KTH/devops-course/issues?q=is%3Aissue+is%3Aopen+label%3Atopic).

Regarding the specific discussions, you are still free to choose different directions. For example, give a concrete scenario and how to use chaos engineering techniques to solve the problem.

Looking forward to further discussions and your PR!

**Comment by nagavem** [comment]
@gluckzhang  Thank you for the quick response :)
We will go into more specifics of the topic and edit the title before presenting but for now the title will be this for the pull request.

I would also like to know,if for the demo it is possible to work in teams of 3?

**Comment by gluckzhang** [comment]
@nagavem , no problem, I just reviewed your pull request.

Based on the [rules of collobration](https://github.com/KTH/devops-course#rules), a group with 3 members is fine. We will evaluate the difficulty and the amount of work according to your team size :)

**Comment by gluckzhang** [comment]
Closed. The issue has been solved.
