### ISSUE TITLE
Similar topic for two assignments

### ISSUE THREAD

**Issue by Mema5** [KTH/devops-course#382]
Hi, I know it has been asked during the initial lecture but I'm not sure about the answer and I can't find it anywhere.

Are we allowed to take a similar topic for two assignments? For example, can I speak about something in a presentation and then write about it in an essay?

**Comment by johannaii** [comment]
I asked about it during lecture 1, and Martin said that you need to choose different topics for each assignment. For instance, you cannot write an essay about CI/CD and then make a presentation about it too. However, I am not sure how strict it is and if it is okay to choose topics in different subfields within CI/CD.

**Comment by gluckzhang** [comment]
Hi all, @johannaii is correct. Students should take different topics for these four tasks in order to learn different perspectives of DevOps. The topics between two assignments should not be exactly the same. However, it's fine if you choose two topics related to the same big domain as testing or security.

We will discuss this in your pull requests :)
