### ISSUE TITLE
For next year: a "progression" in the presentations?

### ISSUE THREAD

**Issue by Mema5** [KTH/devops-course#467]
I think the student presentations are a very good way to get an overview of DevOps. We learn a lot about the pros and the cons of some techniques or tools and in a really pedagogical way!
Unfortunately, there is no order or progression between the topics, and we are kind of jumping from one to another without links between them.

That's why I was wondering: do you think it could be possible to improve this next year? For example having fixed topics and slots that student can pick, obeying to some kind of progression?
Or else asking to everyone who wants to make a presentation to register the task early and then schedule the presentations in an ordered way?

**Comment by gluckzhang** [comment]
Hi @Mema5 , thanks for the great suggestion and we are happy to know you like it!

We will try to improve the presentation arrangement next year. For me, it feels like a trade-off because students get lots of freedom in the current way, but as you say sometimes the presentations on the same day are loosely or not related. The teaching team will definitely have more discussions about this :)

**Comment by Mema5** [comment]
Ok, I guess I have nothing more to add. Thanks for your feedback! I close the issue.
