### ISSUE TITLE
Containerized applications

### ISSUE THREAD

**Issue by GoranPaues** [KTH/devops-course#5]
You should cover how containers can be used when deploying applications. Docker is by far the most commonly used technology for this. It is probably important to cover the differences to virtual machines: How containers are not changed but rather inherited and expanded through the Dockerfiles and how they are more lightweight.

**Comment by monperrus** [comment]
Agree. And beyond the main technology, the main concept to teach is statelessness.

**Comment by SimoneStefani** [comment]
Docker is the thing of the moment and here to stay I guess. I have been discussing with some teachers at KTH to include containers in the basic OS courses. I guess there are 3 levels to discuss containers:

1) The **container**: here the discussion can be quite theoretical (difference with VM as mentioned by @GoranPaues). On the practical side one can show how images can be described as code (i.e. `Dockerfile`) and how containers can be built out of them. Brief introduction to container registries (i.e. [DockerHub](https://hub.docker.com/).
2) Small **set of services**: use Docker Compose to manage few services like a back-end API (e.g. NodeJS or Ruby on Rails) with a database (e.g. PostgreSQL). One needs to be careful with the tech choice since some stacks are harder than others (e.g. PHP + NGINX is tricky). This also gives the opportunity to introduce *networks* and *volumes*.
3) **Container orchestration**: more in #6.

**Comment by monperrus** [comment]
merged with #6 which becomes the reference issue
