### ISSUE TITLE
Can dates and times be added to the lectures on the main page?

### ISSUE THREAD

**Issue by GustavDowling** [KTH/devops-course#557]
I thought we had a lecture today but it seems we do not. Is next lecture on tuesday 21st and if so is that week 5 or 6?

It would be helpful to have dates and times for the lectures on the main page.

**Comment by gluckzhang** [comment]
Hi @GustavDowling , thanks for creating this issue. The next lecture will be on Tuesday 21st April, which is counted as week **5**. On the main `README` page, week number is just a relative number in the course.

In order to avoid inconsistency, the schedule of the course is only announced here:  https://www.kth.se/social/course/DD2482/calendar/ Thanks for understanding!

**Comment by gluckzhang** [comment]
This question has been answered. I will close the issue for now.
